exports.festive = [
    "Diwali",
    "Holi",
    "Eid ul-Fitr",
    "Eid ul-Adha",
    "Christmas",
    "Navratri",
    "Durga Puja",
    "Ganesh Chaturthi",
    "Raksha Bandhan",
    "Dussehra",
    "Pongal",
    "Onam",
    "Baisakhi",
    "Makar Sankranti",
    "Janmashtami",
    "Lohri",
    "Basant Panchami",
    "Guru Nanak Jayanti",
    "Maha Shivaratri",
    "Mahavir Jayanti",
    "Buddha Purnima",
    "Chhath Puja",
    "Karva Chauth",
    "Teej",
    "Bihu",
    "Rath Yatra",
    "Nag Panchami",
    "Karthik Purnima",
    "Navroz",
    "Easter",
    "Muharram",
    "Mahashivratri",
    "Ram Navami",
    "Hanuman Jayanti",
    "Vishu",
    "Ugadi",
    "Gudi Padwa",
    "Cheti Chand",
    "Lohri",
    "Bihu",
    "Ratha Saptami",
    "Raksha Bandhan",
    "Karthikai Deepam",
    "Mahavir Jayanti",
    "Ganga Dussehra",
    "Akshaya Tritiya",
    "Chhath Puja",
    "Kumbh Mela",
    "Hemis Festival",
    "Baisakhi",
    "Bihu",
    "Kite Festival",
    "Chitra Vichitra Fair",
    "International Kite Festival",
    "Pushkar Fair",
    "Hornbill Festival",
    "Puri Rath Yatra",
    "Jaisalmer Desert Festival",
    "Mewar Festival",
    "Kumbhalgarh Festival",
    "Hemis Festival",
    "Goa Carnival",
    "Thrissur Pooram",
    "Chhath Puja",
    "Chandrabhaga Fair",
    "Jodhpur Flamenco and Gypsy Festival",
    "Kila Raipur Sports Festival",
    "Kalachakra Festival",
    "Kila Raipur Sports Festival",
    "Karaga Festival",
    "Konark Dance Festival",
    "Kila Raipur Sports Festival",
    "Velas Turtle Festival",
    "Kumbh Mela",
    "Mahindra Kabira Festival",
    "Republic Day",
    "Independence Day",
    "Gandhi Jayanti",
    "Children's Day",
    "Teacher's Day",
    "Women's Day",
    "Labour Day",
    "World Environment Day",
    "International Yoga Day",
    "World Health Day",
    "World Tourism Day",
    "World AIDS Day",
    "National Youth Day",
    "National Science Day",
    "National Sports Day",
    "National Voters Day",
    "National Girl Child Day",
    "National Unity Day",
    "National Technology Day",
    "National Education Day",
    "Father's day",
    "Mother's day",
    "Mahatma Gandhi Jayanti",
    "Jawaharlal Nehru Jayanti",
    "Subhas Chandra Bose Jayanti",
    "Swami Vivekananda Jayanti",
    "Dr. B.R. Ambedkar Jayanti",
    "Netaji Subhas Chandra Bose Jayanti",
    "Lal Bahadur Shastri Jayanti",
    "Chhatrapati Shivaji Maharaj Jayanti",
    "Rabindranath Tagore Jayanti",
    "Guru Nanak Jayanti",
    "Guru Gobind Singh Jayanti",
    "Rani Lakshmi Bai Jayanti",
    "Sardar Vallabhbhai Patel Jayanti",
    "Birsa Munda Jayanti",
    "Amrita Pritam Jayanti",
    "Acharya Vinoba Bhave Jayanti",
    "Jyotirao Phule Jayanti",
    "Lokmanya Tilak Jayanti",
    "Maharishi Dayanand Saraswati Jayanti",
    "Sarvepalli Radhakrishnan Jayanti"
];
exports.style = [
    "Minimalist",
    "Aesthetic",
    "Abstract"
];
exports.colour = [
    "Black",
    "White",
    "Grey",
    "Red",
    "Pink",
    "Yellow",
    "Green",
    "Blue",
    "Purple",
    "Orange"
];
exports.profileAvtar=[
"https://profile-photo-upload.s3.ap-south-1.amazonaws.com/1.jpg",
"https://profile-photo-upload.s3.ap-south-1.amazonaws.com/2.jpg",
"https://profile-photo-upload.s3.ap-south-1.amazonaws.com/3.jpg"
];


